version: '1.0.0'

services:
  db:
    image: postgres:latest
    container_name: psql
    ports:
      - 5432:5432
    networks:
      - my-network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    

networks:
  my-network:
    driver: bridge
    name: my-network
