version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    restart: always
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=pgsql  # Name of your existing Postgres container
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8ndb
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=Mh@006
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=${n8n_admin_password}
      - N8N_HOST=n8n.mobarakit.com  # Change this if needed
      - WEBHOOK_URL=https://n8n.mobarakit.com/  # Change if using
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - fpt-ecom-network

volumes:
  n8n_data:
    driver: local
    name: n8n_data
  
networks:
  fpt-ecom-network:
    external: true
